name: Build and Push APK

on:
  push:
    branches:
      - main # Change this if needed

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x  # Adjust the version as needed
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Push APK to apk-builds branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan apk-builds
          git rm -rf .
          mkdir apk
          mv build/app/outputs/flutter-apk/app-release.apk apk/app-release.apk
          git add apk/app-release.apk
          git commit -m "Generated APK from latest push"
          git push --force https://x-access-token:${{ secrets.APK_PAT }}@github.com/${{ github.repository }}.git apk-builds
